name: POPBOT
favicon: null
layout_spectrum: 0.1147912044543773
typography_spectrum: 0.5281104182358831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04b3b6'
    - '#58595b'
    - '#111111'
    - '#ee434c'
    - '#b7e8ed'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
